//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Parts
    {
        public int PartId { get; set; }
        public string Engine_type { get; set; }
        public string Fuel_type { get; set; }
        public string Transmission { get; set; }
        public Nullable<int> Number_of_doors { get; set; }
        public string Exhaust_System { get; set; }
        public int CarId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
