//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPartsInfoDetails0701.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQLCarDetailsInfo_07_01Entities : DbContext
    {
        public SQLCarDetailsInfo_07_01Entities()
            : base("name=SQLCarDetailsInfo_07_01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car_Parts> Car_Parts { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
    }
}
