//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R54_M7_Class_04_Work_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        
        public string EmployeeName { get; set; }
        public System.DateTime JoinDate { get; set; }
        public int DepartmentId { get; set; }
        public string Picture { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
